# Generated by Django 6.0.5 on 2026-05-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='kind',
            field=models.CharField(choices=[('paragraph', 'Text'), ('heading1', 'Heading 1'), ('heading2', 'Heading 2'), ('heading3', 'Heading 3'), ('todo', 'To-do'), ('bullet', 'Lista'), ('quote', 'Quote'), ('code', 'Code'), ('divider', 'Divider')], default='paragraph', max_length=20),
        ),
    ]
