# Generated by Django 6.0.5 on 2026-05-31 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_subject_options_note_workspace_page_and_more'),
        ('notes', '0002_alter_block_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Quando preenchido numa página raiz, ela é a pasta dessa matéria.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='academics.subject'),
        ),
    ]
