# Generated by Django 6.0.5 on 2026-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_page_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blocks/files/'),
        ),
        migrations.AlterField(
            model_name='block',
            name='kind',
            field=models.CharField(choices=[('paragraph', 'Text'), ('heading1', 'Heading 1'), ('heading2', 'Heading 2'), ('heading3', 'Heading 3'), ('todo', 'To-do'), ('bullet', 'Lista'), ('quote', 'Quote'), ('code', 'Code'), ('divider', 'Divider'), ('file', 'Arquivo')], default='paragraph', max_length=20),
        ),
    ]
