# Generated by Django 6.0.5 on 2026-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_block_file_alter_block_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_folder',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, atua como uma pasta que contém páginas, mas não contém blocos.'),
        ),
    ]
