# Generated by Django 6.0.5 on 2026-06-08 00:56

import SmartLearning.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_page_is_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blocks/files/', validators=[SmartLearning.security.validate_workspace_file]),
        ),
    ]
