# Generated by Django 6.0.5 on 2026-05-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema'),
        ),
    ]
