# Generated by Django 6.0.5 on 2026-05-31 07:12

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("profiles", "Profile")
    existing = set(Profile.objects.values_list("user_id", flat=True))
    Profile.objects.bulk_create(
        [Profile(user=user) for user in User.objects.exclude(id__in=existing)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_theme'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
