# Generated by Django 6.0.5 on 2026-06-08 00:56

import SmartLearning.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_create_missing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to='profile_photos/', validators=[SmartLearning.security.validate_profile_photo]),
        ),
    ]
