# Generated by Django 6.0.5 on 2026-05-30 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Cadeira')),
                ('professor', models.CharField(blank=True, max_length=120, verbose_name='Professor')),
                ('color', models.CharField(default='#0D9488', help_text='Cor da tag/cadeira (hex).', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadeira',
                'verbose_name_plural': 'Cadeiras',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('estudo', 'Estudo'), ('trabalho', 'Trabalho'), ('prova', 'Prova')], default='estudo', max_length=10, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('professor', models.CharField(blank=True, max_length=120, verbose_name='Professor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de entrega/realização')),
                ('is_done', models.BooleanField(default=False, verbose_name='Terminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_notes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academics.subject', verbose_name='Cadeira')),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ['-created_at'],
            },
        ),
    ]
