# Generated by Django 6.0.5 on 2026-05-31 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
        migrations.AddField(
            model_name='note',
            name='workspace_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_notes', to='notes.page', verbose_name='Página do workspace'),
        ),
        migrations.AlterField(
            model_name='note',
            name='professor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Professor(a)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academics.subject', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#0D9488', help_text='Cor da tag/matéria (hex).', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Professor(a)'),
        ),
    ]
