# Generated by Django 6.0.5 on 2026-05-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_subject_options_note_workspace_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='difficulty',
            field=models.IntegerField(default=3, verbose_name='Dificuldade (1-5)'),
        ),
        migrations.AddField(
            model_name='note',
            name='estimated_time',
            field=models.IntegerField(default=60, verbose_name='Tempo estimado (min)'),
        ),
    ]
