# Generated by Django 6.0.5 on 2026-06-08 00:56

import SmartLearning.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_clear_task_workspace_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('trabalho', 'Trabalho'), ('prova', 'Prova')], default='trabalho', max_length=10, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#0D9488', help_text='Cor da tag/matéria (hex).', max_length=7, validators=[SmartLearning.security.validate_hex_color], verbose_name='Cor'),
        ),
    ]
